name: mylaundry
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0-247.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.19.1
  firebase_auth: 3.4.1
  google_fonts: 3.0.1
  firebase_storage: 10.3.1
  cloud_firestore: 3.2.1
  google_sign_in: 5.3.3
  lottie: 1.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/images/
    - assets/icons/
  uses-material-design: true

